apiVersion: v1
kind: ConfigMap
metadata:
  name: mtb-potential-style
  namespace: default
data:
  mtb-potential.json: |
    {
      "version": 8,
      "name": "Potential MTB Singletrails",
      "sources": {
        "openmaptiles": {
          "url": "mbtiles://tiles.mbtiles",
          "type": "vector"
        }
      },
      "center": [
        8.22929,
        47.48029],
      "zoom": 14,
      "options": {
        "paths": {
          "mbtiles": "/data"
        },
        "domains": [
          "mbtiles.singletrail-map.eu"
        ],
        "formatQuality": {
          "jpeg": 80,
          "webp": 90
        }
      },
      "layers": [
        {
          "id": "mtb_potential",
          "type": "line",
          "source": "openmaptiles",
          "source-layer": "transportation",
          "filter": [
            "all",
            [
              "in",
              "class",
              "path"
            ],
            [
              "!has",
              "mtb_scale"
            ],
            [
              "!in",
              "sac_scale",
              "demanding_mountain_hiking",
              "alpine_hiking",
              "demanding_alpine_hiking",
              "difficult_alpine_hiking"
            ]
          ],
          "layout": {
            "visibility": "visible"
          },
          "paint": {
            "line-color": "rgba(218, 204, 29, 1)",
            "line-width": {
              "stops": [
                [
                  8,
                  3
                ],
                [
                  12,
                  5
                ],
                [
                  14,
                  8
                ]
              ]
            },
            "line-opacity": 0.6
          }
        },
        {
          "id": "mtb_high_potential_path",
          "type": "line",
          "source": "openmaptiles",
          "source-layer": "transportation",
          "filter": [
            "all",
            [
              "in",
              "class",
              "path"
            ],
            [
              "!has",
              "mtb_scale"
            ],
            [
              "in",
              "surface",
              "unpaved",
              "compacted",
              "fine_gravel",
              "gravel",
              "pebblestone",
              "ground",
              "dirt",
              "earth",
              "grass",
              "mud",
              "sand",
              "woodchips"
            ],
            [
              "!in",
              "sac_scale",
              "demanding_mountain_hiking",
              "alpine_hiking",
              "demanding_alpine_hiking",
              "difficult_alpine_hiking"
            ]
          ],
          "layout": {
            "visibility": "visible"
          },
          "paint": {
            "line-width": {
              "stops": [
                [
                  8,
                  3
                ],
                [
                  12,
                  5
                ],
                [
                  14,
                  10
                ]
              ]
            },
            "line-opacity": 0.6,
            "line-color": "rgba(247, 156, 10, 1)"
          }
        }
      ]
    }
