apiVersion: v1
kind: ConfigMap
metadata:
  name: mtb-style
  namespace: default
data:
  mtb.json: |
    {
      "version": 8,
      "name": "MTB Singletrails",
      "sources": {
        "openmaptiles": {
          "url": "mbtiles://tiles.mbtiles",
          "type": "vector"
        }
      },
      "center": [8.27731, 47.47652],
      "zoom": 14,
      "options": {
        "paths": {
          "mbtiles": "/data"
        },
        "domains": [
          "mbtiles.singletrail-map.eu"
        ],
        "formatQuality": {
          "jpeg": 80,
          "webp": 90
        }
      },
      "layers": [
        {
          "id": "mtb",
          "type": "line",
          "source": "openmaptiles",
          "source-layer": "transportation",
          "filter": [
            "all",
            [
              "==",
              "mtb_scale",
              "0"
            ],
            [
              "==",
              "class",
              "path"
            ]
          ],
          "layout": {
            "visibility": "visible"
          },
          "paint": {
            "line-color": "rgba(58, 244, 48, 1)",
            "line-opacity": 0.6,
            "line-width": {
              "stops": [
                [
                  8,
                  3
                ],
                [
                  12,
                  5
                ],
                [
                  14,
                  8
                ]
              ]
            }
          }
        },
        {
          "id": "mtb_s1",
          "type": "line",
          "source": "openmaptiles",
          "source-layer": "transportation",
          "filter": [
            "all",
            [
              "==",
              "mtb_scale",
              "1"
            ],
            [
              "==",
              "class",
              "path"
            ]
          ],
          "layout": {
            "visibility": "visible"
          },
          "paint": {
            "line-color": "rgba(106, 232, 252, 1)",
            "line-width": {
              "stops": [
                [
                  8,
                  3
                ],
                [
                  12,
                  5
                ],
                [
                  14,
                  8
                ]
              ]
            },
            "line-opacity": 0.6
          }
        },
        {
          "id": "mtb_s2",
          "type": "line",
          "source": "openmaptiles",
          "source-layer": "transportation",
          "filter": [
            "all",
            [
              "==",
              "mtb_scale",
              "2"
            ],
            [
              "==",
              "class",
              "path"
            ]
          ],
          "layout": {
            "visibility": "visible"
          },
          "paint": {
            "line-color": "rgba(255, 45, 45, 1)",
            "line-width": {
              "stops": [
                [
                  8,
                  3
                ],
                [
                  12,
                  5
                ],
                [
                  14,
                  8
                ]
              ]
            },
            "line-opacity": 0.6
          }
        },
        {
          "id": "mtb_s3",
          "type": "line",
          "source": "openmaptiles",
          "source-layer": "transportation",
          "filter": [
            "all",
            [
              "==",
              "mtb_scale",
              "3"
            ],
            [
              "==",
              "class",
              "path"
            ]
          ],
          "layout": {
            "visibility": "visible"
          },
          "paint": {
            "line-color": "rgba(135, 13, 13, 1)",
            "line-width": {
              "stops": [
                [
                  8,
                  3
                ],
                [
                  12,
                  5
                ],
                [
                  14,
                  8
                ]
              ]
            },
            "line-opacity": 0.6
          }
        },
        {
          "id": "mtb_s4_plus",
          "type": "line",
          "source": "openmaptiles",
          "source-layer": "transportation",
          "filter": [
            "all",
            [
              "in",
              "mtb_scale",
              "4",
              "5"
            ],
            [
              "==",
              "class",
              "path"
            ]
          ],
          "layout": {
            "visibility": "visible"
          },
          "paint": {
            "line-color": "rgba(0, 0, 0, 1)",
            "line-width": {
              "stops": [
                [
                  8,
                  3
                ],
                [
                  12,
                  5
                ],
                [
                  14,
                  8
                ]
              ]
            },
            "line-opacity": 0.6
          }
        }
      ]
    }

